FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    libicu-dev \
    && rm -rf /var/lib/apt/lists/*

ADD ./install/avaceesipagent-linux /tmp/avaceesipagent-linux

RUN chmod +x /tmp/avaceesipagent-linux

ARG TENANT
ARG DEVREGCODE
ARG EDGEGROUP
ENV TENANT=$TENANT
ENV DEVREGCODE=$DEVREGCODE
ENV EDGEGROUP=$EDGEGROUP

ENTRYPOINT ["/tmp/avaceesipagent-linux"]

CMD ["tenant=", ${TENANT}, "devregcode=", ${DEVREGCODE}, "group=", ${EDGEGROUP} ]
