Start-Transcript -Path C:\scripts\AutomatedLab-Setup-Tree.log -Append
$folders = Get-Content C:\scripts\folderlist.json | ConvertFrom-Json
$monitors = Get-Content C:\scripts\monitorlist.json | ConvertFrom-Json
Remove-Item C:\scripts\folderlist.json
Remove-Item C:\scripts\monitorlist.json
Write-Host $folders
Write-Host $monitors

Write-Host "Importing ControlUp Monitor Modules"
$pathToUserModule = (Get-ChildItem "C:\Program Files\Smart-X\ControlUpMonitor\*ControlUp.PowerShell.User.dll" -Recurse | Sort-Object LastWriteTime -Descending)[0]
$pathToMonitorModule = (Get-ChildItem "C:\Program Files\Smart-X\ControlUpMonitor\*ControlUp.PowerShell.Monitor.dll" -Recurse | Sort-Object LastWriteTime -Descending)[0]
Import-Module $pathToUserModule, $pathToMonitorModule

Write-Host "Creating folder structure"
foreach($folder in $folders) {
    Write-Host $Folder
    $PathParts = $folder -split '\\'
    $ParentPath = [string]::Join('\', $PathParts[0..($PathParts.Length - 2)])
    $Name = $PathParts[-1]

    Write-Host $ParentPath
    Write-Host $Name
    Add-CUFolder -Name $Name -ParentPath $ParentPath -Description 'Generated by AutomatedLab'
}

Write-Host "Creating Batch"
$Batch = New-CUBatchUpdate
foreach($monitor in $monitors) {
    $PathParts = $monitor -split '\\'
    $FolderPath = [string]::Join('\', $PathParts[0..($PathParts.Length - 2)])
    $Name = $PathParts[-1]
    Write-Host "Moving $name to $folderpath"
    Move-CUComputer -Name $Name -FolderPath $FolderPath -Batch $Batch
}

Write-Host "Publishing Updates"
Publish-CUUpdates -Batch $Batch
Stop-Transcript