param(
    [string] $LabName,
    [string] $OrgName,
    [string] $Monitors
)
Start-Transcript -Path C:\scripts\AutomatedLab-Setup-Tree.log -Append
$pathToUserModule = (Get-ChildItem "C:\Program Files\Smart-X\ControlUpMonitor\*ControlUp.PowerShell.User.dll" -Recurse | Sort-Object LastWriteTime -Descending)[0]
$pathToMonitorModule = (Get-ChildItem "C:\Program Files\Smart-X\ControlUpMonitor\*ControlUp.PowerShell.Monitor.dll" -Recurse | Sort-Object LastWriteTime -Descending)[0]
Import-Module $pathToUserModule, $pathToMonitorModule

Add-CUFolder -Name "$LabName" -ParentPath "$OrgName\" -Description 'Generated by AutomatedLab'
Add-CUFolder -Name ControlUp -ParentPath "$OrgName\$LabName\"
Add-CUFolder -Name Agents -ParentPath "$OrgName\$LabName\"

$Batch = New-CUBatchUpdate
foreach($Monitor in ($Monitors -split ',')) {
    Move-CUComputer -Name $Monitor -FolderPath "$OrgName\$LabName\ControlUp" -Batch $Batch
}
Publish-CUUpdates -Batch $Batch
Stop-Transcript